### ISSUE TITLE
Error building project (version mismatch)

### ISSUE THREAD

**Issue by therealdannzor** [blockchainsllc/in3-example-rust#1]
Hi,

### Background
I'm trying to use the `in3` dependency in Rust for the incubed protocol. As of now, the latest published cargo.io version is `0.1.6` as seen here: https://crates.io/crates/in3, and not `1.0.0` as in the example.

In addition, when building with `0.1.6` there is an error.

```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
--> /Users/dkf/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-scale-codec-1.3.4/src/codec.rs:246:1
    |
246 | #[non_exhaustive]
    | ^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/44109
   Compiling serde_urlencoded v0.6.1
   Compiling ethbloom v0.9.2
   Compiling surf v1.0.3
error: aborting due to previous error
```

### Reproduce
1. Clone this repository
2. run `cargo build`
3. get version mismatch
4. edit `Cargo.toml` to latest version
5. get error above

**Comment by hu55a1n1** [comment]
Thanks for the feedback! Technically, we haven't released the rust bindings yet so this example was meant to work with `1.0.0` (whenever that was released), but we appreciate you trying it out. :)
To fix the `#[non_exhaustive]` error please update your rust compiler to a more recent version `>= 1.42.0`. 
Also make sure to check out other requirements on [in3-rs's crates.io page](https://crates.io/crates/in3).

**Comment by therealdannzor** [comment]
Thank you for a quick reply @hu55a1n1, that solved the problem indeed. The reproduce runs without problem now.
